spring:
  application:
    name: msclientes

server:
  port: 0 #Generate random port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${ spring.application.instance_id:${random.value} }